* Radar Signal Processing
Range Doppler map (RDM) and radar signal processing module.

** Description
This Python module provides tools for creating range Doppler maps and includes a variety of functions useful for radar signal processing. It is designed to help researchers and engineers gain an intuition on how RDMs are made.

** Features
- Generate range Doppler maps
- Radar signal processing functions including:
   - Radar range equation
   - Waveform generation
   - Match filtering
   - Radar datacube
   - Doppler processing
   - Skin returns
   - Modulated memory returns

** Installation
To install the module, clone this repository and install with pip:
#+BEGIN_SRC shell
git clone https://github.com/JohnNehls/radar-signal-processing
cd radar-signal-processing
pip install .
#+END_SRC

** Usage
For examples of basic usage, see the examples in [[file:examples][examples]]. To see a script with all  waveform options and contains all supported returns, check out [[file:examples/kitchen_sink.py][kitchen_sink.py]].

** Tests
Scripts displaying the individual components used to create the RDMs are located in [[file:tests][tests]].

** Contributing
Contributions are welcome! Please fork the repository and submit a pull request.

** License
This project is licensed under the GPL-3.0 License - see the LICENSE file for details.
